module.exports = {
    languages: [
        { name: 'JAVASCRIPT' },
        { name: 'PYTHON' },
        { name: 'GO' },
        { name: 'JAVA' },
        { name: 'KOTLIN' },
        { name: 'PHP' },
        { name: 'C#' },
        { name: 'SWIFT' },
        { name: 'R' },
        { name: 'RUBY' },
        { name: 'C' },
        { name: 'MATLAB' },
        { name: 'SCALA' },
        { name: 'TYPESCRIPT' },
        { name: 'SQL' },
        { name: 'NOSQL' },
        { name: 'RUST' },
        { name: 'PERL' },
    ],

    locations: [
        { name: 'AMSTERDAM' },
        { name: 'ATHENS' },
        { name: 'BAKU' },
        { name: 'BELGRADE' },
        { name: 'BERLIN' },
        { name: 'BERN' },
        { name: 'BRATISLAVA' },
        { name: 'BRUSSELS' },
        { name: 'BUCHAREST' },
        { name: 'BUDAPEST' },
        { name: 'CHISNAU' },
        { name: 'COPENHAGEN' },
        { name: 'DUBLIN' },
        { name: 'EDINBURGH' },
        { name: 'HELSINKI' },
        { name: 'KYIV' },
        { name: 'LISBON' },
        { name: 'LJUBLJANA' },
        { name: 'LONDON' },
        { name: 'MADRID' },
        { name: 'MINSK' },
        { name: 'MONACO' },
        { name: 'OSLO' },
        { name: 'PARIS' },
        { name: 'PODGORICA' },
        { name: 'PRAGUE' },
        { name: 'PRISTINA' },
        { name: 'REYKJAVIK' },
        { name: 'RIGA' },
        { name: 'ROME' },
        { name: 'SARAJEVO' },
        { name: 'SKOPJE' },
        { name: 'SOPHIA' },
        { name: 'STOCKHOLM' },
        { name: 'TALLIN' },
        { name: 'TBILISI' },
        { name: 'TIRANA' },
        { name: 'VADUZ' },
        { name: 'VALLETTA' },
        { name: 'VIENNA' },
        { name: 'VILNIUS' },
        { name: 'WARSAW' },
        { name: 'ZAGREB' },
    ]
}